### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" quand j'essaye de me connecter

### ISSUE THREAD

**Issue by Maxcension** [Azuxul/wifirst-autoconnect#1]
Salut ! 

Quand j'essaye de me connecter, j'ai cette erreur de Python qui apparaît. Je n'ai jamais eu le problème avant donc est-ce un problème suite à une modification côté Wifirst?
J'ai essayé de dump, ça me dit juste "None" et j'ai la même erreur quand j'essaye de me connecter directement avec mes identifiants.

Merci d'avance !

```
python wifirst-autoconnect.py -s
Start connexion with saved username and password
Traceback (most recent call last):
  File "C:\Users\maxim\Desktop\Bazard\wifirst\wifirst-autoconnect.py", line 169, in <module>
    main(sys.argv[1:])
  File "C:\Users\maxim\Desktop\Bazard\wifirst\wifirst-autoconnect.py", line 153, in main
    login(False)
  File "C:\Users\maxim\Desktop\Bazard\wifirst\wifirst-autoconnect.py", line 108, in login
    for elem in data[1]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Azuxul** [comment]
Salut,

Malheureusement je ne vais pas pouvoir aider sur ce souci, je n'ai plus accès a un réseau wifirst pour pouvoir effectuer des essais. J'ai rapidement essayé d'utiliser le script mais non connecté au réseau le comportement n'est pas du tout celui attendu. C'est peut-être le fonctionnement de Wifirst qui a changé et qui demanderait une analyse afin de corriger le problème.

Si tu as le courage de reprendre le projet et de corriger ce problème, tu pourrais y arriver. Malheureusement quand j'ai écrit ce script je n'ai pas fait beaucoup de gestion des erreurs de loging pour le debug, donc ce serra un peu plus compliqué.

**Comment by Maxcension** [comment]
Salut !

Tout d'abord, merci de ta réponse. :)
Ensuite, j'aimerais bien reprendre le projet mais actuellement il est un peu au dessus de mes capacités, mais je vais essayer quand j'aurais un peu plus de temps de m'y pencher !

Ma théorie (d'après les quelques tests que j'ai pu faire) est qu'on ne peut plus se connecter via https://smartcampus.wifirst.net/ mais seulement via https://planetcampus.wifirst.net/. Je ne sais pas si c'est le cas de toutes les résidences mais dans la mienne, il y a presque deux ans maintenant, Wifirst est passé de "SmartCampus" à "PlanetCampus", avec une nouvelle page de connexion et un système de wifi public et wifi privé personnel (le point positif est que via le wifi privé, les appareils restent connectés, mais ce n'est pas le cas lorsqu'ils sont connectés via la prise ethernet).
Je pense que jusqu'ici, il était encore possible de se connecter via l'ancienne page de login mais que maintenant il faut forcément passer par la nouvelle (quand j'essaye de me connecter à l'ancienne, cela me redirige automatiquement sur la nouvelle).

Merci en tout cas pour ce script qui me fut utile durant ces deux dernières années, en espérant pouvoir trouver le temps pour pouvoir réparer ça !

**Comment by Azuxul** [comment]
Salut !

C'est totalement possible que ce soit ca et dans ce cas il n'y aurait vraiment pas grand chose a changer. Dans tous les cas, si tu as besoin d'aide les modifs il n'y a pas de soucis. Et ca fait super plaisir de savoir que ce script aura pu aider <3
